version: '3'
services:

  # The core platform, mounts docker control socket into the image
  ids-core:
    image: ashokkumarta/ids-trusted-connector
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      #- ../etc/settings.mapdb:/root/etc/settings.mapdb
      - ../etc/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ../etc/provider-keystore.p12:/root/etc/provider-keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./ids-test-configuration.xml:/root/deploy/ids-configuration.xml
    ports:
      - "8080:8080"
